### PR TITLE
PEAR-1964 -  Age at Index is displaying incorrect values in Cohort Builder

### PR DESCRIPTION
**Pull request by amlehman**
## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by wteouchicago** [comment]
### Issue
1. In develop as well. May be related to the original bug that this PR is trying to fix. For Age At Index, when we enter values as days (e.g. 0-10), it's querying with these values so I end up filtering for 0-10 years. It should be filtering for (0 - 10 days converted  to years, rounded, etc.), which is kind of 🤮 , frankly, but would be consistent with cards with Days-Years toggle.
- I'm tempted to just remove the Days tab for cards whose values are already in Years. This would make it consistent with cDAVE's Age at Index card.
- qn: which change is easier? It doesn't need to be in this PR.

____

looks good otherwise.

**Comment by amlehman** [comment]
@wteouchicago, I think removing the day option would be easier. The facet day/year logic has gotten to be pretty tangled imo. I think it could probably use some reworking before attempting to convert values in another place.

**Comment by wteouchicago** [comment]
OK! I'll create a separate ticket for removing the days option. 👍 

changes here look good. 👍

**Review by paribartandhakal — APPROVED** [review]

**Comment by craigrbarnes** [comment]
Agree this needs some untangling. If we ever get the dictionary mapping  API we can simplify this even more.

**Pull request merged**
