### PR TITLE
fix(PEAR-1615): resolve summary page crashing

### PR DESCRIPTION
**Pull request by alilahrime**
[pear-1615](https://gdc-ctds.atlassian.net/browse/PEAR-1615)

### CODE REVIEW

**Review by craigrbarnes — APPROVED** [review]
Change look fine. No longer seing the error and the search works as expected

**Comment by wteouchicago** [comment]
No longer crashing on gene page or case page.

Some issues:

1. I noticed in the mutations table on the gene and case page that the checkboxes, buttons, and subrow expansion no longer work. I can't tell if it's related to this PR or not since it's crashing in develop for me. Let me know if it's not related and I'll file a separate bug. 
2. I noticed some slowness so I looked in the network tab. There appears to be infinite(?) graphql calls for the ssmTable. This may be the cause of 1. I didn't see this happening in prod-uat but can't test develop.

**Comment by alilahrime** [comment]
> No longer crashing on gene page or case page.
> 
> Some issues:
> 
> 1. I noticed in the mutations table on the gene and case page that the checkboxes, buttons, and subrow expansion no longer work. I can't tell if it's related to this PR or not since it's crashing in develop for me. Let me know if it's not related and I'll file a separate bug.
> 2. I noticed some slowness so I looked in the network tab. There appears to be infinite(?) graphql calls for the ssmTable. This may be the cause of 1. I didn't see this happening in prod-uat but can't test develop.


> No longer crashing on gene page or case page.
> 
> Some issues:
> 
> 1. I noticed in the mutations table on the gene and case page that the checkboxes, buttons, and subrow expansion no longer work. I can't tell if it's related to this PR or not since it's crashing in develop for me. Let me know if it's not related and I'll file a separate bug.
> 2. I noticed some slowness so I looked in the network tab. There appears to be infinite(?) graphql calls for the ssmTable. This may be the cause of 1. I didn't see this happening in prod-uat but can't test develop.

1. I can confirm that the infinite graphql calls were related to the changes, and i think that it caused the other issues if the subrow buttons were clicked first. i don't experience issues with other buttons/checkboxes anymore too after clicking the subrow expansion. 

2. makes sense i think the slowness is related to 1) and should be resolved now.

**Comment by wteouchicago** [comment]
looks good 👍

**Pull request merged**
