### PR TITLE
PEAR-1431 - add ability to rest local filters, move custom filter reset

### PR DESCRIPTION
**Pull request by amlehman**
## Description
NOTE: this is branched off of PEAR-2029-collapsible-filters and that needs to be merged first

## Checklist

- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)
Screenshot 2024-08-27 at 3 18 58 PM
Screenshot 2024-08-27 at 3 19 06 PM

### CODE REVIEW

**Comment by wteouchicago** [comment]
Looking good -- only a few things:

1. When Cancer Gene Census is toggled to false in Mutation Frequency, the Reset Filters button should show up (and it'll count as "1" for the badge). Clicking Reset Filters should set Cancer Gene Census back to its default of true. 

2.  I think the Add a Custom Filter button/strip doesn't quite look like the mockup. Need @cemile-ctds 's eyes. 
- maybe it just needs to be a bit taller so that the reset button part looks closer to a square?
- also, I _think_ the right edge of the strip should be aligned to the right edge of the cards below (not counting the scroll bar for the filters panel). 

3. Similar to 2 above. need @cemile-ctds 's 👁️ . Should the right edge of the Reset Filters link/button be right-aligned with the right edge of the cards below (not counting scroll bar for filters panel).

**Comment by cemile-ctds** [comment]
### Projects: 

- Changing the gap from gap-y-3 to gap-y-4 it aligns better.

Screenshot 2024-08-30 at 12 17 27

### Color of the text:

- Please change the color of the text to `text-primary-content-darker`

Screenshot 2024-08-30 at 12 19 54

### Repository:

- This creates extra space. If there is no custom filter please hide it.

Screenshot 2024-08-30 at 12 20 51

- Changing the gap from gap-y-3 to gap-y-4 it aligns better.

Screenshot 2024-08-30 at 12 26 28

**Comment by wteouchicago** [comment]
Functionality is a-ok now! 👍 

Leaving styling things to @cemile-ctds  ;)

**Comment by amlehman** [comment]
Hi, @cemile-ctds. I addressed those issues, let me know if anything else needs adjusting.

**Comment by cemile-ctds** [comment]
Looks good on my side.

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
