### PR TITLE
PEAR-1264: Font size + header text overflow

### PR DESCRIPTION
**Pull request by alilahrime**
## Description
[pear-1264](https://gdc-ctds.atlassian.net/browse/PEAR-1264)

Screenshot 2023-11-20 at 11 22 08 AM

### CODE REVIEW

**Comment by wteouchicago** [comment]
I don't think this was what @cemile-ctds intended, which was that the text should resize based on the screen size. It seems we've made the text smaller regardless of screen size?
cc @cemile-ctds for her eyes.

**Comment by cemile-ctds** [comment]
@alilahrime Could you update the font size to `text-sm 2xl:text-2xl`? Also, please narrow the gap between the buttons to `gap-2`. We'll handle the spacing consistency issue in a separate ticket, but I believe making this change in this PR will give us some extra space for the totals. Thanks a bunch!

**Comment by cemile-ctds** [comment]
Screenshot 2023-11-21 at 11 35 31
Please revert the gap between icons and text to `gap-0.5`. Also please replace `text-[1rem]` with `text-sm` and `xl:text-xl` with `2xl:text-xl`

-----------

Screenshot 2023-11-21 at 11 24 56
Please change the `gap-4` between the buttons to `gap-2`

-----------

Screenshot 2023-11-21 at 11 35 38
Please omit `text-[1rem]` from this line.

**Comment by wteouchicago** [comment]
looks improved to me, but defer to @cemile-ctds 
I noticed some overflow issues between 1550-1600 width or so, but we can probably live with that for now.

**Comment by cemile-ctds** [comment]
It looks better. I also noticed the overflow issues between 1550-1600 width. Changing the `gap-4` between the buttons to `gap-2` helps.

**Comment by alilahrime** [comment]
> It looks better. I also noticed the overflow issues between 1550-1600 width. Changing the `gap-4` between the buttons to `gap-2` helps.

included this, thank you

**Comment by wteouchicago** [comment]
works nicely now 👍

**Comment by cemile-ctds** [comment]
Looks good on my side.

**Review by paribartandhakal — APPROVED** [review]

**Pull request merged**
