### PR TITLE
PEAR-1967: Hide the Reference Genome section in the file summary page for some types of files

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
To test (file uuid):
for type=masked_methylation_array:
c2d2fef9-49ff-494c-b0ab-b167bbf25611
65222d07-12fe-4a65-b82a-f142e18068a3
89116004-c98f-4c0e-95e2-7ac44efe0368
for Birdseed:
c9abd52d-d9a7-48ca-bdee-80a5911a84c2
8e5188c9-9ed9-44aa-808c-567f18125fa0
353b4340-17e1-445c-bef9-6a14ffc49ab5

## Checklist
- [N/A] Added proper unit tests
- [N/A] Left proper TODO messages for any remaining tasks
- [N/A] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by wteouchicago** [comment]
table is hidden as appropriate, but should the remaining table be half-width like before? looks a bit weird right now. may be worth a check with @cemile-ctds 

Screenshot 2024-07-05 at 2 11 47 PM

**Comment by paribartandhakal** [comment]
> table is hidden as appropriate, but should the remaining table be half-width like before? looks a bit weird right now. may be worth a check with @cemile-ctds
> 
> Screenshot 2024-07-05 at 2 11 47 PM

sure we can ask her. Personally, I prefer this over an empty right section.

**Comment by wteouchicago** [comment]
> sure we can ask her. Personally, I prefer this over an empty right section.

whatever @cemile-ctds decides is fine by me.

👍

**Review by craigrbarnes — COMMENTED** [review]
Code wise this is fine. I will await @cemile-ctds  comments before merging.

**Comment by cemile-ctds** [comment]
I must admit that I liked the full-width version. However, the heading and the cells are too far apart, making it difficult to follow the information in the table.

Therefore, even though it will create white space, please do not use the full width for the table with the heading on the left side.

**Comment by cemile-ctds** [comment]
On second thought, we can also follow the same rules that we have for the summary table if we want to use the full width:
Screenshot 2024-07-09 at 10 40 48

**Comment by wteouchicago** [comment]
@cemile-ctds not sure if you already know this, but most of the time, this area will look like this:
Screenshot 2024-07-09 at 10 51 48 AM

but now, a small portion will not have the reference genome part. 

will it be weird for users that some file summary pages' analysis section have a different layout from others?

**Comment by wteouchicago** [comment]
discussed with @cemile-ctds  - please go ahead with her suggestion for the full width. fyi @paribartandhakal

**Comment by paribartandhakal** [comment]
> On second thought, we can also follow the same rules that we have for the summary table if we want to use the full width: Screenshot 2024-07-09 at 10 40 48

This has been done. Please let me know if it looks okay.

**Comment by cemile-ctds** [comment]
This looks good on my side.

**Comment by wteouchicago** [comment]
full width table looks good.

found a bug that seems to be only on this branch (at least it's not in develop). Steps:
- go to http://localhost:3000/files/c9abd52d-d9a7-48ca-bdee-80a5911a84c2
- click on the source file: 1ede33c8-6f98-425f-9f30-4a4b7791b07c 
-- (or just try to load http://localhost:3000/files/1ede33c8-6f98-425f-9f30-4a4b7791b07c directly)

Screenshot 2024-07-09 at 4 37 41 PM

**Review by wteouchicago — CHANGES_REQUESTED** [review]
see comment on runtime error

**Review by wteouchicago — APPROVED** [review]
looks good. no more crashy crash. 👍

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
