### PR TITLE
PEAR-1963: cDAVE - Search input should remain fixed and not scroll

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
1. Style Changes
2. Code Clean Up

@wteouchicago please verify the overall behavior of CDave specially the fields panel on the left. Thank you 🙇‍♂️ 

## Checklist
- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

https://github.com/NCI-GDC/gdc-frontend-framework/assets/101295912/f3cad20e-e66e-4367-af7b-d7d116e02cc2

### CODE REVIEW

**Comment by wteouchicago** [comment]
The scroll behaviour looks right to me -- cemile would be the best judge and we can have her look after merge. I also sanity-checked cDAVE in general, but not every nook and cranny of functionality. Let me know if there's something I should look out for.

One thing -- do you think we need some padding on the right side of the search box? so that it's rightmost edge is aligned with the rightmost edge of the blue section headers (e.g. Demographic)?

**Review by craigrbarnes — CHANGES_REQUESTED** [review]
Agree with @wteouchicago to add right padding to the search input for better alignment with the facet header's right section.

Some issues with the less button:

1. The size of the + button is now different than the - button:

image

image

2. Clicking on the less button (the minus icon) does not close the expanded list. Clicking on the "show less" text does work  as before

**Comment by paribartandhakal** [comment]
> Agree with @wteouchicago to add right padding to the search input for better alignment with the facet header's right section.
> 
> Some issues with the less button:
> 
> 1. The size of the + button is now different than the - button:
> 
> image
> 
> image
> 
> 2. Clicking on the less button (the minus icon) does not close the expanded list. Clicking on the "show less" text does work  as before

Good call. I fixed both the issues and fixed a failing unit test.

**Comment by paribartandhakal** [comment]
> The scroll behaviour looks right to me -- cemile would be the best judge and we can have her look after merge. I also sanity-checked cDAVE in general, but not every nook and cranny of functionality. Let me know if there's something I should look out for.
> 
> One thing -- do you think we need some padding on the right side of the search box? so that it's rightmost edge is aligned with the rightmost edge of the blue section headers (e.g. Demographic)?

I updated the styling.

**Comment by craigrbarnes** [comment]
Items 1 and 2 are addressed.  Everything else looks fine.

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
