### PR TITLE
adding smoke-test tags for Data Portal v2 automation testing

### PR DESCRIPTION
**Pull request by AmyCMP**
## Description
while testing use this command `gauge run --tags "smoke-test" specs`

### CODE REVIEW

**Comment by bpierce01** [comment]
Where you marked spec files to be a smoke test, I think we only need 1 test per folder. Thoughts @uc-pperumala ?

**Comment by uc-pperumala** [comment]
Thanks, @AmyCMP! It looks good. However, I had a question. @bpierce01 this may apply more to you. I am wondering why are we placing `smoke-test` at the file level and not at the scenario-level? 

Technically, smoke tests should just be handful of test scenarios.

**Comment by bpierce01** [comment]
> Thanks, @AmyCMP! It looks good. However, I had a question. @bpierce01 this may apply more to you. I am wondering why are we placing `smoke-test` at the file level and not at the scenario-level?
> 
> Technically, smoke tests should just be handful of test scenarios.

My thought it should be on the spec level for two reasons:
1. The spec files are already small enough to where it's the building block of a test
2. Some scenarios are dependent on pre-existing scenarios having been executed 

Overall, suggestion is for the PR is to reduce the number of spec files that have the smoke test tag

**Review by bpierce01 — CHANGES_REQUESTED** [review]
reduce the number of spec files that have the smoke test tag

**Comment by AmyCMP** [comment]
> Thanks, @AmyCMP! It looks good. However, I had a question. @bpierce01 this may apply more to you. I am wondering why are we placing `smoke-test` at the file level and not at the scenario-level?
> 
> Technically, smoke tests should just be handful of test scenarios.



> reduce the number of spec files that have the smoke test tag

The number of spec files with smoke test tags have been reduced..

**Review by bpierce01 — APPROVED** [review]

**Pull request merged**
