### PR TITLE
PEAR-1433: Add a save cohort error modal

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
Added a new modal to be shown when there's a problem saving a cohort. I also got rid of the notification we were showing before after verifying it with @wteouchicago.

## Checklist
- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

https://github.com/NCI-GDC/gdc-frontend-framework/assets/101295912/e6775c89-8bc4-4a0f-9a90-947ffd3afb80

### CODE REVIEW

**Comment by wteouchicago** [comment]
Works for me -- I triggered it by going to qa-pink, saving, then switching to qa-orange, making some changes to the cohort, and then saving. 👍 I wasn't able to find  a way to trigger it for Save-As or Replace, FYI.

**Review by amlehman — APPROVED** [review]

**Comment by wteouchicago** [comment]
I did more testing and was able to trigger it for Save-As and Replace. I think the Save Cohort Error modal isn't showing up if it's not the first save of the cohort, e.g.:
- save a cohort
- edit your context_id 
- make some change to the cohort, then try to save
- I see the "there was a problem saving your cohort" notification, but not the modal

I'm fine if we do the remaining piece in a follow-up later ticket.

**Comment by paribartandhakal** [comment]
> I did more testing and was able to trigger it for Save-As and Replace. I think the Save Cohort Error modal isn't showing up if it's not the first save of the cohort, e.g.:
> 
> * save a cohort
> * edit your context_id
> * make some change to the cohort, then try to save
> * I see the "there was a problem saving your cohort" notification, but not the modal
> 
> I'm fine if we do the remaining piece in a follow-up later ticket.

should be fixed now 🤞

**Comment by wteouchicago** [comment]
works for me. 👍

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
