### PR TITLE
PEAR-1937 - Alternatives to complex images - Body plot image

### PR DESCRIPTION
**Pull request by amlehman**
## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)
https://github.com/NCI-GDC/gdc-frontend-framework/assets/4624053/599097b0-fcab-4aae-9125-afb55d5632c2

### CODE REVIEW

**Comment by wteouchicago** [comment]
1. Minor. Can we change the anchor name from `#high-quality-datasets-card` to `#high-quality-datasets`? (It'll be exposed to the world and "card" may be confusing.) `#high-quality-datasets-section` could work too.
2. I couldn't figure out how to activate the links on the chart using the kb. I tried enter and space.

**Comment by wteouchicago** [comment]
KB activation of link works now. This isn't my area, but should the keyboard focus return to the same link on the chart after you dismiss the modal that shows up?

**Comment by amlehman** [comment]
Hi @cemile-ctds 👋, any thoughts on:
1) skip link styling
2) tooltip positioning
for this ticket?

**Comment by wteouchicago** [comment]
focus now returns to the originating link after the modal closes. things look ok from my side, but pending cemile's expertise.

**Comment by wteouchicago** [comment]
Spoke briefly to Cemile. If needed, we can change "Skip Navigation" to "Skip Charts" or "Skip Visualizations".

**Comment by cemile-ctds** [comment]
1- Skip link before the chart:
Skip to main content - Skip to content
-  The skip link should be placed before the chart title (Cases by Major Primary Site). Currently, the screen reader reads the title first, followed by the skip link.
- The color contrast ratio of the skip link is insufficient. I recommend using darker colors instead of white.
- "Skip Navigation" does not provide users with clear information about their current location or the destination of this link. We should change this to one of @wteouchicago's suggestions.

2- Keyboard navigation:
https://github.com/NCI-GDC/gdc-frontend-framework/assets/100392615/1e523054-c1df-438f-be26-ef26f4e97209

When tabbing, the tooltips appear as expected. However, when tabbing back up, the page doesn't scroll with the focus. The focus remains behind the top fixed header/navigation, and the tooltip appears over them. Please see the attached image and video for reference.
TAB2

3- Screen reader:
https://github.com/NCI-GDC/gdc-frontend-framework/assets/100392615/b9fb5812-d683-4917-b19d-d241750a3f60

The screen reader first reads the title of the chart, then jumps to the bottom of the chart, reads each chart item individually, and finally goes back to the top of the list to read the tooltips. Please see the attached video for reference.

I'm not sure if we can implement this, but here is my suggestion for this flow:
- The screen reader reads the chart title.
- Moves down and reads the "1000s of cases."
- Skips numbers
- Moves back up to the chart items and reads the item along with the number of cases/files.

**Comment by amlehman** [comment]
Hi @cemile-ctds, I addressed 1 and 3. Please have a look and let me know what you think.

For 2, I think this is a general problem with how the header is positioned and I'm not sure how to address it without losing the "sticky" behavior on the header. You can see it happening to a less obvious extent other places on the site:

https://github.com/user-attachments/assets/be386caf-906a-425f-8f06-a13c2e51dd68

**Comment by cemile-ctds** [comment]
All three issues that I reported previously have been fixed and look good on my side.

**Comment by wteouchicago** [comment]
looks good to me for the stuff i know how to check :) 👍

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
