### PR TITLE
PEAR-1678: Summary modal header button visibility on focus

### PR DESCRIPTION
**Pull request by alilahrime**
[pear-1678](https://gdc-ctds.atlassian.net/browse/PEAR-1678)

## Screenshots/Screen Recordings (if Appropriate)
Screenshot 2024-01-02 at 11 06 37 AM

### CODE REVIEW

**Comment by paribartandhakal** [comment]
I don't see the changes reflecting to the focused state of the button. It only works when the button is hovered over. The focus reaches the button but the border is not visible as asked by the ticket. cc. @alilahrime @cemile-ctds

**Comment by cemile-ctds** [comment]
> I don't see the changes reflecting to the focused state of the button. It only works when the button is hovered over. The focus reaches the button but the border is not visible as asked by the ticket. cc. @alilahrime @cemile-ctds

The focus state indicates keyboard accessibility, highlighting the element currently receiving keyboard input. As Pari mentioned, the hover state style is changing (which we'd prefer not to happen on this ticket; hover state consistency will be addressed in a separate ticket). However, the focus state is still not visible. We need the focus state to match the style of the cohort bar. Please check the attached image for reference.
Screenshot 2024-01-02 at 14 34 12

**Comment by alilahrime** [comment]
> > I don't see the changes reflecting to the focused state of the button. It only works when the button is hovered over. The focus reaches the button but the border is not visible as asked by the ticket. cc. @alilahrime @cemile-ctds
> 
> The focus state indicates keyboard accessibility, highlighting the element currently receiving keyboard input. As Pari mentioned, the hover state style is changing (which we'd prefer not to happen on this ticket; hover state consistency will be addressed in a separate ticket). However, the focus state is still not visible. We need the focus state to match the style of the cohort bar. Please check the attached image for reference. Screenshot 2024-01-02 at 14 34 12

I understand, removed the hover style changes. this is what it looks like on focus now. is this good?
Screenshot 2024-01-04 at 10 27 31 AM

**Comment by cemile-ctds** [comment]
> I understand, removed the hover style changes. this is what it looks like on focus now. is this good? 

This looks good @alilahrime Could you also add this style to [X] close button?

Screenshot 2024-01-04 at 14 51 13

**Comment by cemile-ctds** [comment]
I've reviewed other summary pages (project, gene, mutation, case, file). Additionally, the focus style should be incorporated into the Project and File summary page headers. 
Project: http://localhost:3000/v2/projects/TCGA-BRCA
File: http://localhost:3000/v2/files/76a0fe52-63a8-4d15-b7e8-d1e4baddce49

**Comment by wteouchicago** [comment]
@alilahrime  -- pari/cemile are investigating some alternative solutions rq. please hold on further changes to this PR until they finish the investigation.

**Comment by paribartandhakal** [comment]
This has been put in this PR: https://github.com/NCI-GDC/gdc-frontend-framework/pull/908

**Pull request closed without merging**
