### PR TITLE
PEAR-2050 - Incorrect GraphQL request creating for mutating gene and mutation sets when search is applied

### PR DESCRIPTION
**Pull request by amlehman**
## Description
+ PEAR-1865 - Apply search bar filters to JSON/TSV files
(- the TSV download on case summary: https://gdc-ctds.atlassian.net/browse/DEV-2889)

## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by wteouchicago** [comment]
## Issues
1. The file summary page's Annotations table's JSON doesn't seem to respond to the search, e.g. this file summary http://localhost:3000/files/1b306916-fe77-469e-8c86-43e8b606b1b8

2. The mutations set I created isn't adding up as expected:
- Brain cohort from home page. Mutation Frequency > Mutations tab.
- type "EGFR" in the search box - 75 mutations
- save it as a set "foo"
- search for "IDH1" - 6 mutations
- add these mutations to the "foo" set 
- go to Manage Sets and look at the size of "foo". I got 169 items. I expected 81.

**Comment by amlehman** [comment]
Hi, @wteouchicago. I corrected those issues.

**Comment by wteouchicago** [comment]
looks good! 👍

**Review by craigrbarnes — APPROVED** [review]
Code changes are fine

**Pull request merged**
