### PR TITLE
PEAR-1941: add error message to survival plot when no data to display

### PR DESCRIPTION
**Pull request by ocshawn**
## Description
add error message to survival plot when no data to display

## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Review by craigrbarnes — APPROVED** [review]
Works as defined in the ticket. Code changes are also fine.

**Review by wteouchicago — DISMISSED** [review]
The "No Survival Data available for this Cohort Comparison" message should only show up for the survival plot in the Cohort Comparison app. It's currently showing up in Mutation Frequency as well (I didn't check if it'll show up in cDAVE).

**Comment by wteouchicago** [comment]
for me, the latest change has caused survival plot to not be displayed in Mutation Frequency and cDAVE.

**Comment by wteouchicago** [comment]
looks good! 👍

**Review by craigrbarnes — APPROVED** [review]
Changes look fine

**Pull request merged**
