### PR TITLE
PEAR-2159: Fix projects json download

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
Also fixes: https://gdc-ctds.atlassian.net/browse/PEAR-2189
## Checklist
- [N/A] Added proper unit tests
- [N/A] Left proper TODO messages for any remaining tasks
- [N/A] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

https://github.com/user-attachments/assets/16cd7308-3abc-4a88-9ae8-e5bdbe723371

### CODE REVIEW

**Comment by wteouchicago** [comment]
The error is gone, but now, when I search in the table, the JSON no longer reflects the results of the search. It contains all the projects. Same if I use the filters on the left.

**Comment by wteouchicago** [comment]
looks good 👍

**Review by amlehman — APPROVED** [review]

**Comment by paribartandhakal** [comment]
> The error is gone, but now, when I search in the table, the JSON no longer reflects the results of the search. It contains all the projects. Same if I use the filters on the left.

Please verify this one more time for both Projects and Annotation tables.

**Comment by wteouchicago** [comment]
looks good! 👍 👍

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
