### PR TITLE
PEAR-1944: Adjusting facet card font sizes

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
Waiting for @cemile-ctds' approval.
## Checklist
- [N/A] Added proper unit tests
- [N/A] Left proper TODO messages for any remaining tasks
- [N/A] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)
facet

### CODE REVIEW

**Comment by wteouchicago** [comment]
This looks fine. I noticed a few small things not explicitly specified, but we may want to tweak for consistency. We can also do these later.

1. The labels in the filter buttons for MF is 12px. should it be 14px?
Screenshot 2024-06-10 at 3 38 15 PM

2. Not sure if the placeholder text for date ranges should be 14px - I am guessing yes.
Screenshot 2024-06-10 at 3 40 40 PM

3. Definitely no idea if the calendar should all be 14px. Maybe wait for @cemile-ctds on this and we can adjust in later PR if needed.
Screenshot 2024-06-10 at 3 41 19 PM

**Comment by paribartandhakal** [comment]
> This looks fine. I noticed a few small things not explicitly specified, but we may want to tweak for consistency. We can also do these later.
> 
> 1. The labels in the filter buttons for MF is 12px. should it be 14px?
> 
> Screenshot 2024-06-10 at 3 38 15 PM
> 2. Not sure if the placeholder text for date ranges should be 14px - I am guessing yes.
> 
> Screenshot 2024-06-10 at 3 40 40 PM
> 3. Definitely no idea if the calendar should all be 14px. Maybe wait for @cemile-ctds on this and we can adjust in later PR if needed.
> 
> Screenshot 2024-06-10 at 3 41 19 PM

I went ahead and fixed all including calendar date.

**Comment by wteouchicago** [comment]
looks good. 👍 i noticed the size of the font for the dates in the calendar is 13px, but i think that is perfectly fine. 🤞 :)
edit: the font is showing up as 14 on pari's end. maybe it's...weird rounding? :)

**Review by craigrbarnes — APPROVED** [review]
Changes look fine

**Pull request merged**
