### PR TITLE
PEAR-1672: Change styles to make header, context bar, cohort bar responsive

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
Style changes. Mostly flex-wrap.

## Checklist
- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)
https://github.com/NCI-GDC/gdc-frontend-framework/assets/101295912/c0e2bcbb-56a5-4abf-92e2-0aa5192f170d

### CODE REVIEW

**Comment by wteouchicago** [comment]
This seemed mostly ok to me. At a lower width (1280) and 200% zoom, I think the header isn't wrapping?

**Comment by paribartandhakal** [comment]
> This seemed mostly ok to me. At a lower width (1280) and 200% zoom, I think the header isn't wrapping?

Yes it isn't wrapping. We should be okay as this is highly unlikely.

**Comment by wteouchicago** [comment]
ok by me 👍

**Comment by cemile-ctds** [comment]
This looks fone on my side.

**Review by ocshawn — APPROVED** [review]
looks good

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
