### PR TITLE
PEAR-1564 - Cohort Save-As feature

### PR DESCRIPTION
**Pull request by amlehman**
## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)
Screenshot 2023-11-29 at 10 13 26 AM
Screenshot 2023-11-29 at 10 13 40 AM
Screenshot 2023-11-29 at 10 13 55 AM

### CODE REVIEW

**Comment by bpierce01** [comment]
For the dropdown box (the thing containing save and save as), could you give it a data-testid "dropdown-menu-options"

**Review by bpierce01 — CHANGES_REQUESTED** [review]
For the dropdown box, please give it a data-testid of "dropdown-menu-options"
Screenshot 2023-11-29 at 3 32 09 PM
The image has an example of it in other dropdown boxes elsewhere in the data portal

**Comment by cemile-ctds** [comment]
1. The save icon has a margin on the right side; please remove it.
Screenshot 2023-12-04 at 14 19 20

**Comment by wteouchicago** [comment]
Works great! Save button nicer now too. 👍 💾 👍

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
