### PR TITLE
PEAR-2186: Update download icon.

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Checklist
- [N/A] Added proper unit tests
- [N/A] Left proper TODO messages for any remaining tasks
- [N/A] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by wteouchicago** [comment]
looks good -- I didn't see any instances of download icons being unchanged. 👍 

one thing, because the updated icon takes up less width than the old one (at least to my eyes), I wonder if we need to move the icon nearer to the text in buttons. here's an example (Repository):
Screenshot 2024-09-30 at 12 40 01 PM

maybe @cemile-ctds has thoughts.

**Comment by amlehman** [comment]
You don't have to address this here but looking at this PR made me think maybe we should have a file we import our "canonical" versions of the icons we are using all over the app (download, save, close, search, etc.) and then all consuming components could import from there.

**Review by amlehman — APPROVED** [review]

**Comment by paribartandhakal** [comment]
> You don't have to address this here but looking at this PR made me think maybe we should have a file we import our "canonical" versions of the icons we are using all over the app (download, save, close, search, etc.) and then all consuming components could import from there.

Good idea and I feel like there's already a ticket for it, right @wteouchicago?

**Comment by wteouchicago** [comment]
> > You don't have to address this here but looking at this PR made me think maybe we should have a file we import our "canonical" versions of the icons we are using all over the app (download, save, close, search, etc.) and then all consuming components could import from there.
> 
> Good idea and I feel like there's already a ticket for it, right @wteouchicago?

I'm not that prescient! But yes, I'll make one ;)

**Comment by paribartandhakal** [comment]
> > > You don't have to address this here but looking at this PR made me think maybe we should have a file we import our "canonical" versions of the icons we are using all over the app (download, save, close, search, etc.) and then all consuming components could import from there.
> > 
> > 
> > Good idea and I feel like there's already a ticket for it, right @wteouchicago?
> 
> I'm not that prescient! But yes, I'll make one ;)

I must be hallucinating. I was so confident I saw it. Maybe it was this ticket.

**Pull request merged**
