### PR TITLE
update the proteinpaint-client version to 2.39.1

### PR DESCRIPTION
**Pull request by siosonel**
## Description

@craigrbarnes Should I base this branch off `release/jacob`? I can open another branch/PR as needed. Also, please let me know what the failing check is for, my local lint and tests passed, using `npx jest src/features/proteinpaint/*.test.*` from the portal-proto dir.

Fixes:
Related to JIRA tickets
- Fix the navigation of matrix and gene expression controls by keyboard
- Option to override the matrix default of not rendering samples that are not annotated for any dictionary term, for more intuitive behavior in gene-centric use-cases
- Matrix should update when the filter0 changes while the geneset edit UI is displayed
- Detect empty hits before trying to render bam variants
- Display an initial geneset edit UI when the GDC default matrix genes is empty

Related to internal PP fixes before the 2.12 build
- Disable the term group menu for hierCluster gene expression term group, and remove the 'edit' and 'sort' options for other hier cluster term groups
- Exclude embedder state in the standalone recover tracked state, for the matrix and hier cluster undo/redo

Fixes to issues found in lower 2.39 releases (was not deployed to qa-orange) 
- Ensure that the zoom controls has valid dimensions on update, in case it was initially rendered in an invisible div
- Reenable the handling of genome-level termdbs in the migrated server route

## Checklist

- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by craigrbarnes** [comment]
I can merge into `jacob/release` and nto `develop` as well. 
There is a failing buiild:
```
src/features/proteinpaint/GeneExpressionWrapper.tsx(111,9): error TS2322: Type 'Timeout' is not assignable to type 'number'.
src/features/proteinpaint/OncoMatrixWrapper.tsx(111,9): error TS2322: Type 'Timeout' is not assignable to type 'number'.
```

**Comment by siosonel** [comment]
> I can merge into `jacob/release` and nto `develop` as well. There is a failing buiild:
> 
> ```
> src/features/proteinpaint/GeneExpressionWrapper.tsx(111,9): error TS2322: Type 'Timeout' is not assignable to type 'number'.
> src/features/proteinpaint/OncoMatrixWrapper.tsx(111,9): error TS2322: Type 'Timeout' is not assignable to type 'number'.
> ```

Thanks, Craig, I've pushed a type fix. I'm not able to see gitlab CI logs, so I'll need this help hopefully rarely. Also, I  meant if I should start my local branch off `release/jacob` instead of `develop`, in case that will make it easier to merge later by the approver.

**Comment by craigrbarnes** [comment]
That fixed the issue.  Could you merge this with `release/jacob` and change the base of this PR to `release/jacob`

**Comment by siosonel** [comment]
@craigrbarnes If I rebase on release/jacob, I'll have to force push - that should be okay, right? I've merged jacob into this branch for now, but I can do the rebase instead if you're okay that I force push.

**Comment by craigrbarnes** [comment]
Don't force push. The changes seem to be what they should be, with one exception: I see changes to `.gitlab-ci.yml` which is not expected. Can you fix it so only your changes are in the PR?

**Comment by siosonel** [comment]
Ok, I can create a different branch with only my changes on top of `release/jacob`. I think that will mean that I have to open another PR, which is okay, I'll just copy the PR description and refer to this PR (to be closed).

**Pull request closed without merging**
