### PR TITLE
PEAR-1695 - 508 compliance, hide images not conveying content from screenreader

### PR DESCRIPTION
**Pull request by amlehman**
## Description
Hides any decorative images from screenreader. From https://www.w3.org/WAI/tutorials/images/decorative/ 

>  Images may be decorative when they are:
> 
> Visual styling such as borders, spacers, and corners;
> Supplementary to link text to improve its appearance or increase the clickable area;
> Illustrative of adjacent text but not contributing information (“eye-candy”);
> Identified and described by surrounding text.

## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by cemile-ctds** [comment]
Please hide...
1. ... the divider on tool cards and Manage sets.
Screenshot 2024-01-05 at 14 14 03
Screenshot 2024-01-05 at 15 07 39

2. ... carets on the buttons with dropdown functionality.

3. ... the icons on the summary/table view toggle button.
Screenshot 2024-01-05 at 15 15 17

4. As you did for the facet card buttons please hide the SVG images of the cohort bar buttons and add `aria-label` to the buttons.
Screenshot 2024-01-05 at 14 37 10

**Comment by amlehman** [comment]
Hi @cemile-ctds, I made the requested updates.

**Comment by wteouchicago** [comment]
@cemile-ctds ping

**Review by cemile-ctds — APPROVED** [review]
All requested changes have been implemented, and they work as expected with screen readers. Some changes may result in a merge conflict with the "LineItem68_2" branch.

**Review by craigrbarnes — APPROVED** [review]

**Pull request merged**
