### PR TITLE
PEAR-1789 - Remove unused pages

### PR DESCRIPTION
**Pull request by amlehman**
## Description
Delete 

## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by amlehman** [comment]
Do we want to delete the styleguide [code](https://github.com/NCI-GDC/gdc-frontend-framework/tree/develop/packages/portal-proto/src/features/styleguide) as well or leave it in place @craigrbarnes ?

**Comment by wteouchicago** [comment]
Verified those 4 pages are getting me to the 404 page. 👍 

FWIW, craig mentioned that, if needed, he would build a new app or page for the style guide. I _think_ that means we should keep the code around still? 🤷‍♀️

**Review by craigrbarnes — APPROVED** [review]
Looks fine to me

**Comment by craigrbarnes** [comment]
> Verified those 4 pages are getting me to the 404 page. 👍
> 
> FWIW, craig mentioned that, if needed, he would build a new app or page for the style guide. I _think_ that means we should keep the code around still? 🤷‍♀️

We can pull the code from git later.

**Pull request merged**
