### PR TITLE
PEAR-1720: Remove prefilled Unsaved_Cohort name when saving cohort

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Checklist

- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)

https://github.com/NCI-GDC/gdc-frontend-framework/assets/101295912/99540edf-511b-4703-85a9-73fab805025b

### CODE REVIEW

**Comment by wteouchicago** [comment]
looks good. 👍 

philosophical/naive qn: "Unsaved_Cohort" is the unsaved cohort's name. It's also the name we disallow, which is why we don't want to prefill the field with this name. Would it be clearer down the road for future people if we name the constant something else, e.g. INVALID_COHORT_NAME? 

We also specify it here: https://github.com/NCI-GDC/gdc-frontend-framework/blob/develop/packages/portal-proto/src/components/Modals/SaveCohortModal.tsx#L272 
- would it be nice to refer to the same const?

more curious than anything. :)

**Comment by paribartandhakal** [comment]
> looks good. 👍
> 
> philosophical/naive qn: "Unsaved_Cohort" is the unsaved cohort's name. It's also the name we disallow, which is why we don't want to prefill the field with this name. Would it be clearer down the road for future people if we name the constant something else, e.g. INVALID_COHORT_NAME?
> 
> We also specify it here: https://github.com/NCI-GDC/gdc-frontend-framework/blob/develop/packages/portal-proto/src/components/Modals/SaveCohortModal.tsx#L272
> 
> * would it be nice to refer to the same const?
> 
> more curious than anything. :)

Signed, Sealed, Delivered!

Please verify. I did and it's the same. Thank you for your _philosophical_ question. 😄

**Comment by wteouchicago** [comment]
works the same for me as well. 👍

**Review by craigrbarnes — APPROVED** [review]
Good refactoring and clean code

**Pull request merged**
