### PR TITLE
PEAR-2055+2034: Fix styling issues in CDAVE

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
@cemile-ctds has approved these changes. 

## Checklist
- [ ] Added proper unit tests
- [ ] Left proper TODO messages for any remaining tasks
- [ ] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Review by craigrbarnes — APPROVED** [review]
Code charges are fine. Icons are visibly smaller

**Comment by wteouchicago** [comment]
I'm not quite seeing the button sizes being the same - the download and reset buttons on the left look bigger than the download button on the right.
Screenshot 2024-10-04 at 11 32 09 AM

chart y-axis labels no longer being cut off though!

**Comment by paribartandhakal** [comment]
> I'm not quite seeing the button sizes being the same - the download and reset buttons on the left look bigger than the download button on the right. Screenshot 2024-10-04 at 11 32 09 AM
> 
> chart y-axis labels no longer being cut off though!

It's fixed now. They were two diff components.

**Comment by wteouchicago** [comment]
looks good! 👍

**Pull request merged**
