### PR TITLE
PEAR-1970: Display '0 days' correctly in case summary follow-up (and other places)

### PR DESCRIPTION
**Pull request by paribartandhakal**
## Description
Fixed issue where ageInDays value of 0 was not displayed correctly in case summaries. Added a check to ensure '0 days' is shown accurately.

## Checklist
- [X] Added proper unit tests
- [N/A] Left proper TODO messages for any remaining tasks
- [N/A] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by wteouchicago** [comment]
works for me, but the fix feels a little dirty ;) 👍

**Comment by paribartandhakal** [comment]
> works for me, but the fix feels a little dirty ;) 👍

I updated it. I verified it via manual checking and unit tests are passing too. Do you mind quickly verifying it one more time?

**Comment by wteouchicago** [comment]
still works for me :) 👍

**Review by craigrbarnes — APPROVED** [review]
The changes appear to be fine. Maybe we can reorganize the code to make the logic clearer in the future.

**Pull request merged**
