### PR TITLE
PEAR-2232 - Adjust Sample Sheet download buttons

### PR DESCRIPTION
**Pull request by amlehman**
## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

## Screenshots/Screen Recordings (if Appropriate)
Screenshot 2024-12-02 at 3 41 10 PM

Screenshot 2024-12-02 at 3 44 16 PM

Screenshot 2024-12-02 at 3 41 26 PM

### CODE REVIEW

**Comment by wteouchicago** [comment]
In the Cart, for the menu items in the Clinical and Biospecimen downloads, could you put the JSON download above the TSV download? This would make it consistent with those buttons in the Cohort Bar. 

Looks good otherwise.

**Comment by cemile-ctds** [comment]
Looks good on my end, and I agree with Wendy's comment about the placement of the JSON/TSV dropdown items.

**Comment by amlehman** [comment]
Hi, @wteouchicago, I've made that update.

**Comment by wteouchicago** [comment]
looks great! thanks @amlehman! 👍

**Review by paribartandhakal — APPROVED** [review]

**Pull request merged**
