### PR TITLE
PEAR-1856 - Don't reset local filters if active cohort has changes

### PR DESCRIPTION
**Pull request by amlehman**
## Checklist

- [x] Added proper unit tests
- [x] Left proper TODO messages for any remaining tasks
- [x] Scanned for web accessibility with **aXe**, and mitigated or documented
      flagged issues

### CODE REVIEW

**Comment by wteouchicago** [comment]
## Issues
1. If the user switches to a different cohort, then the local filters should reset.

**Comment by wteouchicago** [comment]
Just one more place (that is admittedly silly) -- Projects app: local filters should reset if the user switches to a different cohort.

**Comment by wteouchicago** [comment]
works great! 👍

**Review by paribartandhakal — APPROVED** [review]

**Review by craigrbarnes — APPROVED** [review]
Changes look fine

**Pull request merged**
